global:
  storageClass:
  imagePullSecrets:
    - docker-registry-secret

nameOverride: common
fullnameOverride: common

image:
  repository: common
  tag: common
  pullPolicy: Always

replicaCount: 1

revisionHistoryLimit: 5

terminationGracePeriodSeconds: 60

containerPort: 8080

service:
  type: ClusterIP
  targetPort: 8080
  port: 8080

  ## @param service.extraPorts - Extra ports to expose in the service (normally used with the `sidecar` value)
  ##
  extraPorts:

ingress:
  enabled: true
  certManager: false
  annotations:
    kubernetes.io/ingress.class: ingress

  #path: /api # Default path for extraHosts

  hosts:
    - host: common.example.com
      paths:
        - /api
  tls:
    - secretName: tls-secret-name
      hosts:
        - common.example.com

  ## @param ingress.pathType - Ingress Path type
  ##
  pathType: ImplementationSpecific

  ## @param ingress.extraHosts - The list of additional hostnames to be covered with this ingress record.
  ## extraHosts:
  ## - name: test2.example.com
  ##   path: /
  ##
  extraHosts: []

  ## @param ingress.extraTls - The tls configuration for additional hostnames to be covered with this ingress record.
  ## extraTls:
  ## - hosts:
  ##     - test2.example.com
  ##   secretName: tls-secret-name-2
  ##
  extraTls: []

livenessProbe: {}
readinessProbe: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: []

tolerations: []

affinity: {}

## @param env - Array containing env vars to configure service
## For example:
## env:
##   - name: DATABASE_URL
##     value: mysql://127.0.0.1:3306
##   - name: LOG_LEVEL
##     value: debug
##
env:

## @param envSecret - Enable/Disable ingesting envs from secret containing extra env vars (in case of sensitive data)
## You must to create secret with name of service before
##
envSecret: false

## @param extraVolumes - Array to add extra volumes. Requires setting `extraVolumeMounts`
## For example:
## extraVolumes:
##   - name: assets
##     persistentVolumeClaim:
##       claimName: assets-pvc
extraVolumes:

## @param extraVolumeMounts - Array to add extra mounts. Normally used with `extraVolumes`
## For example:
## extraVolumeMounts:
##   - name: assets
##     mountPath: /tmp/assets
extraVolumeMounts:

## @param hostAliases - Add deployment host aliases
##
hostAliases: []

## @param updateStrategy.type - Set up update strategy for deploy.
## Example:
## updateStrategy:
##   type: RollingUpdate
##   rollingUpdate:
##     maxSurge: 25%
##     maxUnavailable: 25%
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

## @param sidecars - Attach additional containers to the pod
## e.g.
## - name: your-image-name
##   image: your-image
##   imagePullPolicy: Always
##   ports:
##   - name: portname
##     containerPort: 1234
##
sidecars:

## @param initContainers - Add additional init containers to the pod
## e.g.
## - name: your-image-name
##   image: your-image
##   imagePullPolicy: Always
##   ports:
##   - name: portname
##     containerPort: 1234
##
initContainers:

## @param kubeVersion Force target Kubernetes version (using Helm capabilities if not set)
##
kubeVersion:

